#!/usr/bin/env python3
"""Measure the rotation rest-day distribution from MLB statsapi game logs.

For every starting pitcher on an active MLB roster, pulls their pitching game
log, extracts the dates of their *starts*, and tallies the calendar-day gaps
between consecutive starts. The pooled distribution is what the cadence SP model
in app/sim.py uses to project a pitcher's remaining turns from his last start.

Gaps are clamped to a sane rotation band: gaps below MIN_GAP (doubleheader /
data quirks) and above MAX_GAP (IL stints, demotions, all-star break) are
dropped as non-rotation noise. The output `REST_DAY_WEIGHTS = {...}` is intended
to be pasted into sim.py (like the VMR table from analyze_variance.py).

Self-contained — reads no local DB, so it works before pitcher_starts is
populated. All data is public, unauthenticated. Run-time ~1 min.

Usage: .venv/bin/python scripts/analyze_cadence.py
"""

from __future__ import annotations

import sys
import time
from collections import Counter
from datetime import date

import httpx

# Allow running from repo root
sys.path.insert(0, ".")
from app.teams import MLBAM_TO_ESPN

MLB_URL = "https://statsapi.mlb.com/api/v1"
SEASON = 2026
MIN_GAP = 3            # below this = doubleheader / data quirk, not a turn
MAX_GAP = 8            # above this = IL stint / demotion / break, not a turn
MIN_STARTS = 4         # need a few starts to contribute meaningful gaps


def fetch_rosters(client: httpx.Client) -> list[dict]:
    players = []
    for team_id in MLBAM_TO_ESPN:
        try:
            r = client.get(f"{MLB_URL}/teams/{team_id}/roster?rosterType=active",
                           timeout=30.0)
            r.raise_for_status()
            for p in r.json().get("roster", []):
                players.append({
                    "id": p["person"]["id"],
                    "name": p["person"]["fullName"],
                    "abbr": p["position"]["abbreviation"],
                })
        except Exception as e:  # noqa: BLE001
            print(f"  team {team_id} skipped: {e}", file=sys.stderr)
    return players


def fetch_start_dates(client: httpx.Client, person_id: int) -> list[date]:
    r = client.get(
        f"{MLB_URL}/people/{person_id}/stats",
        params={"stats": "gameLog", "season": SEASON, "group": "pitching"},
        timeout=30.0,
    )
    r.raise_for_status()
    stats_arr = r.json().get("stats", [])
    if not stats_arr:
        return []
    out: list[date] = []
    for s in stats_arr[0].get("splits", []) or []:
        stat = s.get("stat") or {}
        if not stat.get("gamesStarted", 0):
            continue
        d = s.get("date")
        if not d:
            continue
        try:
            out.append(date.fromisoformat(d[:10]))
        except ValueError:
            continue
    return out


def main() -> None:
    gaps: Counter[int] = Counter()
    pitchers_used = 0

    with httpx.Client() as client:
        print("Fetching active MLB rosters...", file=sys.stderr)
        players = fetch_rosters(client)
        pitchers = [p for p in players if p["abbr"] in ("P", "TWP")]
        print(f"  got {len(players)} players, {len(pitchers)} pitchers",
              file=sys.stderr)

        for i, p in enumerate(pitchers):
            try:
                dates = sorted(set(fetch_start_dates(client, p["id"])))
            except Exception:  # noqa: BLE001
                continue
            if len(dates) < MIN_STARTS:
                continue
            pitchers_used += 1
            for a, b in zip(dates, dates[1:]):
                gap = (b - a).days
                if MIN_GAP <= gap <= MAX_GAP:
                    gaps[gap] += 1
            if (i + 1) % 30 == 0:
                print(f"  pitcher {i+1}/{len(pitchers)}", file=sys.stderr)

    total = sum(gaps.values())
    if total == 0:
        print("No rotation gaps found — is the season underway?", file=sys.stderr)
        sys.exit(1)

    mean = sum(g * n for g, n in gaps.items()) / total

    print(f"\n# Auto-generated by scripts/analyze_cadence.py")
    print(f"# Season {SEASON}, MLB statsapi game logs as of {time.strftime('%Y-%m-%d')}")
    print(f"# {pitchers_used} SPs, {total} consecutive-start gaps, "
          f"mean rest = {mean:.2f} days")
    for g in sorted(gaps):
        bar = "#" * round(40 * gaps[g] / max(gaps.values()))
        print(f"#   {g}d  n={gaps[g]:>4}  {gaps[g]/total:5.1%}  {bar}")
    print("REST_DAY_WEIGHTS = {")
    for g in sorted(gaps):
        print(f"    {g}: {gaps[g] / total:.3f},")
    print("}")


if __name__ == "__main__":
    main()
